services:
  photon:
    build:
      context: .
      dockerfile: Dockerfile
    image: jefure/photon-geocoder:latest
    volumes:
      - data:/photon/photon_data
    ports:
      - 2322:2322

volumes:
  data:
    driver: local
